apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-mysql-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lab2-mysql-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lab2-mysql-app
    spec:
      containers:
      - image: mysql:5.6
        imagePullPolicy: Always
        name: lab2-mysql-app
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        resources:
          requests:
            memory: 1024Mi
            cpu: 500m
          limits:
            memory: 2048Mi
            cpu: 1000m
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-efs-claim
