apiVersion: v1
kind: Service
metadata:
  name: lab2-wordpress-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: lab2-wordpress-app
