apiVersion: v1
kind: Service
metadata:
  namespace: lab2-ns
  name: lab2-mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: lab2-mysql-app
